[package]
name = "semantic_index"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/semantic_index.rs"

[dependencies]
anyhow.workspace = true
collections.workspace = true
fs.workspace = true
gpui.workspace = true
language.workspace = true
lmdb = "0.8.0"
project.workspace = true
settings.workspace = true
smol.workspace = true
util = { workspace = true }
worktree.workspace = true

[dev-dependencies]
env_logger.workspace = true
fs = { workspace = true, features = ["test-support"] }
futures.workspace = true
gpui = { workspace = true, features = ["test-support"] }
language = { workspace = true, features = ["test-support"] }
languages.workspace = true
project = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
util = { workspace = true, features = ["test-support"] }
worktree = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
